version: '3.8'
services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - C:\laragon\www\laravelNgnix:/var/www
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    # volumes:
    #   - .:/var/www
    volumes:
      - C:\laragon\www\laravelNgnix:/var/www

